<a href="https://colab.research.google.com/github/Jobhert/Activity/blob/main/Assignment6_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Linear Algebra for ECE
### Labaratory 6 : Matrix Operation


Now that you have a fundamental knowledge about representing and operating with vectocs as well as the fundamentals of matrices, we'll try to the same operations with matrices even more.




###Objectives

At the end of this activity you will be able to:
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intemrediate equations.
3. Apply matrix algebra in engineering solutions. 

##Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

##Transposition

One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. So for a matrix *A* its transpose is denoted as $A^T$.
So for example.


$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$


This can now be achived programmaticaly by using np.transpose() or using the T method

In [2]:
A = np.array([
    [1, 2, 5],
    [5, -1, 0],
    [0, -3, 3]
])
A

array([[ 1,  2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [3]:
AT1 = np.transpose(A)
AT1

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [7]:
AT2 = A.T
AT2

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [8]:
np.array_equiv(AT1, AT2)

True

In [6]:
B = np.array([
    [1, 2, 3, 4],
    [1, 0, 2, 1],
])
B.shape

(2, 4)

In [9]:
np.transpose(B).shape

(4, 2)

In [10]:
B.T.shape

(4, 2)

Try to create your own matrix (you can try non-squares) to test transposition

In [15]:
C=np.array([
    [4,7,9],
    [1,2,8]        
])
C.shape

(2, 3)

In [16]:
np.transpose(C).shape


(3, 2)

In [17]:
C.T.shape


(3, 2)

##Dot product

In [18]:
X = np.array([
    [1,2],
    [0,1]
])
Y = np.array([
    [-1,0],
    [2,2]
])

In [19]:
np.dot(X, Y)

array([[3, 4],
       [2, 2]])

In [20]:
X.dot(Y)

array([[3, 4],
       [2, 2]])

In [21]:
X @ Y

array([[3, 4],
       [2, 2]])

In [23]:
np.matmul(X, Y)

array([[3, 4],
       [2, 2]])

Test

In [25]:
D=np.array([
     [1,1,0],
     [0,1,1],
     [1,0,1]       
])
E=np.array([
     [5,8,0],
     [3,1,1],
     [4,6,7]       
])

In [26]:
np.dot(D, E)

array([[ 8,  9,  1],
       [ 7,  7,  8],
       [ 9, 14,  7]])

In [27]:
D.dot(E)

array([[ 8,  9,  1],
       [ 7,  7,  8],
       [ 9, 14,  7]])

In [28]:
D @ E

array([[ 8,  9,  1],
       [ 7,  7,  8],
       [ 9, 14,  7]])

In [29]:
np.matmul(D, E)

array([[ 8,  9,  1],
       [ 7,  7,  8],
       [ 9, 14,  7]])

##Print

In [30]:
A = np.array([
    [2, 4],
    [5, -2],
    [0, 1]
])
B = np.array([
    [1, 1],
    [3, 3],
    [-1, -2]
])
C = np.array([
    [0, 1, 1],
    [1, 1, 2]
])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 2)
(3, 2)
(2, 3)


In [31]:
A @ C

array([[ 4,  6, 10],
       [-2,  3,  1],
       [ 1,  1,  2]])

In [32]:
B @ C

array([[ 1,  2,  3],
       [ 3,  6,  9],
       [-2, -3, -5]])

## Shape

In [ ]:
X = np.array([
    [1, 2, 3, 0],
])
Y = np.array([
    [1, 1],
])
print(X.shape)
print(Y.shape)
